from marshmallow import fields
from schema import ma

# Define the Customer schema
class CustomerSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    name = fields.String(required=True)
    email = fields.String(required=True)
    phone = fields.String(required=True)

    class Meta:
        fields = ("id", "name", "email", "phone")

# Create instances of the schemas
customer_schema = CustomerSchema()
customers_schema = CustomerSchema(many=True)
